### ISSUE TITLE
Update Figures page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/eLife-JATS-schematron#123] opened 2020-01-30 12:05 UTC
- [x] Add AQ standard text if part labels not right
- [x] Add guidance about what to do when figures are cited in captions without part labels
- [x] Add guidance about lowercase letters in legends (reword to avoid the full list page and instead advise to check against rest of article)
- [x] Change figure permissions rules to subsections (not bullet points)
- [x] Add template text to ‘license-p’ part of xml example (‘Figure X is reproduced from Smith et al. (2020) with permission. It is not covered by the CC-BY 4.0 licence and further reproduction of this panel would need permission from the copyright holder.’)
- [x] Add creative commons link to ‘Further reading’
- [x] Team given feedback?
- [ ] Make new ticket for working on team comments

**Comment by naushinthomson** [comment] 2020-01-31 13:33
@bcollins14 @JGilbert-eLife @FAtherden-eLife Does this page now look okay? For James' benefit, I also made additions from #118 and #114

**Comment by Melissa37** [comment] 2020-01-31 13:39
>This page is about figures associated with articles. Most articles will have figures and figure supplements, and some will also have videos, video supplements and source data or source code.

Can I suggest changing this to:
Most articles will have figures and figure supplements. Figures may also also have video supplements and/or source data and/or source code. Figure supplements can also have these assets too.

**Comment by Melissa37** [comment] 2020-01-31 13:41
It would be ideal if this document is included in the Wiki:

https://github.com/elifesciences/XML-mapping/blob/master/elife_file_naming_2016_08_25.md

Whether the fiel naming is split out per "topic" page or left as a seperate "section" in the Wiki is up to you guys! But if the former, need to add that to the checklist to cross check it's been covered, and if the latter, add a new issue to cover it. This doc has not been checked in a while so will need QC :-)

**Comment by Melissa37** [comment] 2020-01-31 13:52
>Please alert Production if any figures or figure supplements consist only of tables. This is strongly discouraged and we may need to contact the authors to request changing these to main tables, supplementary files or source data.

As this is a resource for all, could we make this less specific to Exeter? Maybe change to:

We strongly discourage authors from providing tables represented as figures or figure supplements because figures are flat images and the contents of them cannot be mined or re-used without the need to rekey the content. The preference would be to ask the author to provide this information as a table in Word or Excel format and for this to them be added to the article. If the author has not cited this "figure" in the text (for instance because it is a figure supplement) please ask her/him to cite the new table in the main text. 

However, the author may also be given the option to convert it to source data. If it is a figure supplement this would become figure x - source data x; if it is a main figure this would become source data attached to the document as a whole.

@naushinthomson could you paste some examples of these to the Wiki? For instance sometimes we'd let them go and other times be more insistent. It would be good to provide an example of each

**Comment by Melissa37** [comment] 2020-01-31 13:57
>Image files containing multiple pages are not allowed. The author must be queried to supply the image as a single page or to split the individual pages up into separate figures or figure supplements. If the authors have included unlabeled images in their article file that do not correspond to the main figures, a query should be raised with eLife Production to determine how to treat these images. In most cases, these images will need to be treated as chemical structures or schema.

Suggest changing to:

If an author provides a PDF of an image over multiple pages we cannot process that as a single figure.
Use your judgment - if each "page" contains a small image that could be a part of a complete composite figure query the author to supply the image as a single page with part labels. 
If the images on each page are a full figure and combining the images into one figure would render them unreadable ask the author to split the individual pages up into separate figures or figure supplements. 
If the authors have included unlabeled images in their article file that do not correspond to the main figures, a query should be raised with eLife Production to determine how to treat these images. In most cases, these images will need to be treated as chemical structures or schema.

@naushinthomson could you add some example screenshots of chemical structures/schema?

**Comment by Melissa37** [comment] 2020-01-31 14:02
Suggest changing this heading 
>Figures in the PDF
To:
PDF version

Suggest changing 
>In the PDF version of eLife articles for research content, there are three allowed sizings for figure blocks (the space into which a figure should be fitted):

To:
For research content (Features content templates have separate rules, see XXX)

@naushinthomson would it be possible to add some screenshots of the PDF figure size variations?

**Comment by JGilbert-eLife** [comment] 2020-01-31 14:03
My initial comment is that we need to consider the order this information appears - I don't think the current order quite works . . .

For example, we've got licensing information advice before the legends as a whole, whereas I think logically those should be the other way around.

**Comment by JGilbert-eLife** [comment] 2020-01-31 14:07
We should also think about integrating this doc: https://docs.google.com/document/d/1G6XSkti5s3xDlz3d8A1kXDBEZDugi7tUyeQAGKMOgXY/edit#heading=h.4noujeghif23

Probably as its own page!

**Comment by Melissa37** [comment] 2020-01-31 14:09
Suggest changing:
>If the previously published content was published in eLife or another open-access journal using a CC BY license, there is no problem with them doing so as long as they follow the terms of the license laid out above (provide a proper citation of the work and make it clear what exactly they have reproduced).

To:
If the previously published content was published under a CCBY or CC0 license, the work must be properly attributed and credited (provide full citation details and license). If this matches the license of this article it does not need to be tagged differently in the underlying XML because it is following the license of the article. However, if the article you are working on is CC0, but the reproduced figure is CCBY, this needs to be indicated in the underlying XML and so requires specific tagging.

**Closed** 2020-08-05 11:57 UTC
Labels: Wiki
